### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by raharrison** [chimbori/crux#19]
Any plans on pushing a new release? Seems like there have been a lot of change since 2.2.0 which is the last on Maven Central.

**Comment by chimbori** [comment]
Since this is a major change, I’m waiting for a production app using the new Crux to be out in the field for a while before treating it as stable. Thanks!

**Comment by chimbori** [comment]
Here you go: https://github.com/chimbori/crux/releases/tag/v3.0.0

(Not yet on Maven as commented above).

**Comment by EmpowrCo** [comment]
Is there a changelog?
