### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by sigpwned** [chimbori/crux#2]
I just re-created the pull request that was lost in the transition, mostly to let you know I see your spiffy new repo and I'm tracking. :)

The pull request is here: https://github.com/chimbori/crux/pull/1

I'd recommend against merging that PR for now. I'll continue to work on that branch / PR and will let you know as soon as we're ready to deploy to Maven Central. It'll take some work from you -- e.g., you'll need to do some DNS/webpage stuff to take ownership of the "com.chimbori" group in Maven Central -- but I'll try make it as turnkey as possible!

**Comment by chimbori** [comment]
Thanks, Andy!

I did some of the setup steps earlier, here’s the tracker: 
https://issues.sonatype.org/browse/OSSRH-36184?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by psefranek** [comment]
Hi guys! 
I just want to ask what's the current state of releasing this library to Maven central.

Thanks and have a nice day.
Pavel

**Comment by mufumbo** [comment]
this would make it much easier to try this project, how are you guys adding it right now? cloning the git repo locally?

**Comment by chimbori** [comment]
Do the instructions to use Jitpack work for you? It’s still Maven-based, but not Maven Central.

https://github.com/chimbori/crux/blob/master/README.md#import-crux-via-gradle

**Comment by mufumbo** [comment]
yes, but after googling "crux jetpack maven" I get to the snacktory page only. 

the only way is to go to jitpack.com and put https://github.com/chimbori/crux/ as a link. 
that gives access to this url where I can press the maven tab and figure out. 
https://jitpack.io/#chimbori/crux

I'm just saying, if you add Maven README.md it might gain a bunch of new adopters. 

the reason why maven central is so convenient is that I would just google "crux mvn" and it would become the first result.

BTW, I actually already had it crux setup in my project like this: 
```
        <dependency>
            <groupId>com.github.chimbori</groupId>
            <artifactId>crux</artifactId>
            <version>2.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

I wonder if it should deprecate log4j.

**Comment by chimbori** [comment]
> yes, but after googling "crux jetpack maven" I get to the snacktory page only.

There’s a typo, it’s `jitpack` not `jetpack`.

> the only way is to go to jitpack.com and put https://github.com/chimbori/crux/ as a link.

That’s one way, but you can simply just follow the instructions in the README of this repo to get that URL.

> I'm just saying, if you add Maven README.md it might gain a bunch of new adopters.

Completely agree, but configuring to publish to Maven Central is non-trivial, and we just haven’t gotten to it yet. In parallel, everyone who wants to use Crux has been doing so successfully using Jitpack, so the only issue is discoverability.

> the reason why maven central is so convenient is that I would just google "crux mvn" and it would become the first result.

Agreed!

> BTW, I actually already had it crux setup in my project like this:
> I wonder if it should deprecate log4j.

Crux doesn’t have any dependencies, but I’m not well-versed with the syntax you’ve mentioned about how `<exclusion>` works. I think you could safely omit all that fluff and simply keep the dependency referring to Crux only.

BTW, if you are familiar with Maven and are able to help publish this to Maven Central, we would totally appreciate that! The main bottleneck is not the work to publish, but in figuring out how to do it for a Maven publishing newbie.

**Comment by psefranek** [comment]
I have found a good article describing how to publish a project to Maven Central: https://dzone.com/articles/publish-your-artifacts-to-maven-central

The essential step is to create an issue in Sonatype JIRA (https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134). 

Sample issue can be found here: https://issues.sonatype.org/browse/OSSRH-24465

Hope this helps a bit

**Comment by chimbori** [comment]
[See upthread](https://github.com/chimbori/crux/issues/2#issuecomment-377955183) for the Sonatype issue already created. I think I paused work at the signing and publishing stages, because Jitpack was already so convenient.

Thanks for the article! It’s good to have everything laid out in one long format instead of in multiple places.

**Comment by chimbori** [comment]
Crux is now available via Maven Central:
http://repo1.maven.org/maven2/com/chimbori/crux/crux

**Comment by mufumbo** [comment]
boom! great job @chimbori !

**Comment by psefranek** [comment]
Many thanks @chimbori. 

Could you please update your README.md by inserting Maven coordinates?

    <dependency>
      <groupId>com.chimbori.crux</groupId>
      <artifactId>crux</artifactId>
      <version>2.0.2</version>
    </dependency>

It will help new users get started.
