### ISSUE TITLE
ConcurrentModificationException in PostprocessHelpers

### ISSUE THREAD

**Issue by johngray1965** [chimbori/crux#2]
Appears to be that its deleting in loop where deleting isn't a safe operation.

I believe it should use an Iterator with delete on the iterator itself.

John

java.util.ConcurrentModificationException
                         E      at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
                         E      at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
                         E      at com.chimbori.crux.articles.PostprocessHelpers.removeDisallowedAttributes(PostprocessHelpers.java:193)
                         E      at com.chimbori.crux.articles.PostprocessHelpers.removeDisallowedAttributes(PostprocessHelpers.java:191)
                         E      at com.chimbori.crux.articles.PostprocessHelpers.removeDisallowedAttributes(PostprocessHelpers.java:191)
                         E      at com.chimbori.crux.articles.PostprocessHelpers.postprocess(PostprocessHelpers.java:85)
                         E      at com.chimbori.crux.articles.ArticleExtractor.extractContent(ArticleExtractor.java:62)

**Comment by chimbori-dev** [comment]
Fixed in 7400331
