### ISSUE TITLE
Is Crux's minSdk 19? Usage of java.nio.charset.StandardCharsets causes crashes pre-19 since it added to Android SDK only since 19.

### ISSUE THREAD

**Issue by arunkumar9t2** [chimbori/crux#5]
The source file just contains some [constants](http://grepcode.com/file_/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/nio/charset/StandardCharsets.java/?v=source).

Android documentation [link](https://developer.android.com/reference/java/nio/charset/StandardCharsets.html).

It looks like it is safe to copy over but I wanted to confirm if you intend to keep Crux minSdk 19.

**Comment by manastungare** [comment]
Crux is a pure Java library, so there's no minSdk as such. But if you want to copy the UTF8 constant inline to avoid the dep on nio, that's fine! Send a PR?

**Comment by chimbori-dev** [comment]
Crux is a pure Java library, so there’s no concept of `minSdkVersion` per se.

Looks like `StandardCharsets` is the only usage that’s problematic on SDK < 19, so it seems fine to inline.

**Comment by chimbori-dev** [comment]
Fixed in 54c2c2f

**Comment by arunkumar9t2** [comment]
Thanks!
